 # 5 Numpy Functions You Didn’t Know You Needed






NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python.The NumPy library contains multidimensional array and matrix data structures. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

NumPy lets us create multi dimensional arrays and lets us perform simple as well as complex operations like indexing, broadcasting, slicing, matrix multiplication. Today we’ll see how to organize your NumPy arrays better and compute some interesting operations using following functions. The functions are 



- numpy.sort
- numpy.argmax
- numpy.where
- numpy.count_nonzero
- numpy.extract


The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [47]:
!pip install jovian --upgrade -q

In [48]:
import jovian

In [49]:
jovian.commit(project='zerotoanalyst-numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "renuverma55/zerotoanalyst-numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/renuverma55/zerotoanalyst-numpy-array-operations


'https://jovian.ai/renuverma55/zerotoanalyst-numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [50]:
import numpy as np

## Function 1 - np.sort

This function returns a sorted copy of an array.Please note that the original array do not change. 
The function takes the below parameter.

Parameters :

 - arr : Array to be sorted.
 - axis : Axis along which we need array to be started.(Optional)
 - order : This argument specifies which fields to compare first.(Optional)
 - kind : [‘quicksort’{default}, ‘mergesort’, ‘heapsort’]Sorting algorithm.(Optional)


In [63]:
# Example 1 -working .
# Lets sort the array along tha last axis
arr1 = [[21, 10, 6], 
        [6, 4, 1],
        [7 ,3 ,8 ]]

np.sort(arr1)

array([[ 6, 10, 21],
       [ 1,  4,  6],
       [ 3,  7,  8]])

Above array is sorted along the last axis. the default value of axis is -1 which sort along the last axis.

In [64]:
# Example 2 - working.
# Lets flattern the array and sort it.
arr1 = [[21, 10, 6], 
        [6, 4, 1],
        [7 ,3 ,8 ]]


np.sort(arr1, axis = None)

array([ 1,  3,  4,  6,  6,  7,  8, 10, 21])

As you can see that the array is flattern and sorted.

In [65]:
# Example 3 breaking
arr1 = [[21, 10, 6], 
        [6, 4, 1],
        [7 ,3 ,8 ]]

np.sort(arr1, axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

We got an error saying that the specified axis is out of bounds. We had given a 2 dimensional array with axis (0,1). As the third dimension doesn’t exist for the given array, we get the error. To fix this error, make sure the axis you specify is within the bounds of the dimensions of the given array.

Use sort() function when you have a collection or an array of random unordered data but the use case requires you to sort the data in organized manner.

In [66]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "renuverma55/zerotoanalyst-numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/renuverma55/zerotoanalyst-numpy-array-operations


'https://jovian.ai/renuverma55/zerotoanalyst-numpy-array-operations'

## Function 2 - numpy.argmax

Returns the indices of the maximum values along an axis.The function takes the below parameter.

Parameter

 - arr : Input array
 - axis : Axis along which we need array to be started.(Optional)
 - out : If provided, the result will be inserted into this array.(Optional)
 - keepdims : bool.If this is set to True, the axes which are reduced are left in the result as dimensions with size one. With this option, the result will broadcast correctly against the array.(Optional)

In [69]:
# Example 1 - working
arr2 = [[100, 25, 12],
       [13, 15, 160]]
np.argmax(arr2)

5

arr2 has max value at position 5. Hence it showing 5 as argmax output.
In case of multiple occurrences of the maximum values, the indices corresponding to the first occurrence are returned.

In [70]:
# Example 2 - working
# Get the index of the highest value in a 2-D array 
arr2 = [[100, 10, 12],
       [13, 15, 160]]
np.argmax(arr2, axis=0)

array([0, 1, 1])

Output shows the position of the maximum value along the axis = 0 (column wise)

In [71]:
# Example 3 - Breaking
arr2 = [[25, 1, 12],
       [13, 150, 100],
       [100, 150, 12]]
np.argmax(arr2,axis =2)

AxisError: axis 2 is out of bounds for array of dimension 2

We got an error saying that the specified axis is out of bounds. We had given a 2 dimensional array with axis (0,1). As the third dimension doesn’t exist for the given array, we get the error. To fix this error, make sure the axis you specify is within the bounds of the dimensions of the given array.

Use np.argmax() function to get the index of the maximum value of a sequence of random variables

In [12]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/zerotoanalyst-numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/zerotoanalyst-numpy-array-operations


'https://jovian.ai/aakashns/zerotoanalyst-numpy-array-operations'

## Function 3 -  numpy.where

The function numpy.where(condition, x,y) return elements chosen from x or y depending on condition.if condition is true return x, if condition is false return y.

The function numpy.where(condition) will return the __index position__ of values that fall in a certain condition when the condition alone is provided and value of x and y are not given.

In [11]:
# Example 1 - working
a = np.arange(10)
print(a)
arr3= np.where(a < 5, a, 10*a)
print(arr3)


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]


We check for the values that are greater than 10. The values that were greater than 10, were kept as they were. The values that were lesser than 10 were multiplied by 10.

In [12]:
# Example 2 -working
# return index of element that satisfied the condition
b = np.arange(4*5).reshape(4,5)
#Where x is greater than 2, returns index position
print(b)
print(np.where(b>14))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(array([3, 3, 3, 3, 3]), array([0, 1, 2, 3, 4]))


Here the function return index position of the element that satisfied the condition, on this example it returns all element index(row, column) that are greater than 14.

In [14]:
# Example 3 - breaking
x=np.array([[[1,2],[2,3]],[[4,5],[6,7]],[[8,9],[10,11]]])
print('The orginal array is')
print(x)
np.where((x>3),x)


The orginal array is
[[[ 1  2]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


ValueError: either both or neither of x and y should be given

The error is because the third argument is missing. We must provide all three arguments or both second and third arguments should be omitted.

The where function is a very good function to know the index of outliers in the data for analysis and to get those outliers. This is a really useful function for conditional problems where there are different operations to be performed for those that satisfy a condition and for those that do not.

In [72]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "renuverma55/zerotoanalyst-numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/renuverma55/zerotoanalyst-numpy-array-operations


'https://jovian.ai/renuverma55/zerotoanalyst-numpy-array-operations'

## Function 4 - numpy.count_nonzero

Counts the number of non-zero values in the array a.

In [73]:
# Example 1 - working
arr4 = np.eye(4)
a= np.count_nonzero(arr4)
print("There are {} non zero value in the array".format(a))

There are 4 non zero value in the array


We created an identity matrix which has 4 rows and 3 columns. We then found how many nonzero values are present in the given array.

In [98]:
# Example 2 - working
arr4 =  [[100, 10, 12,0],
       [13, 0, 160,6]]
count = np.count_nonzero(arr4, axis = 0)
print("Nonzero conut on the input array along the axis = 0 is ",count)

count1 = np.count_nonzero(arr4, axis = 1)
print("Nonzero conut on the input array along the axis = 1 is ",count1)

Nonzero conut on the input array along the axis = 0 is  [2 1 2 1]
Nonzero conut on the input array along the axis = 1 is  [3 3]


We can get the count of nonzero array by usig the axis.

In [99]:
# Example 3 - breaking
a= np.array([1,2,3,0,3,1,2,3,1,0,0])
a_nonzero = np.count_nonzero(a, axis = 1) #axis out of bounds
a_nonzero

AxisError: axis 1 is out of bounds for array of dimension 1

As we can see here, the axis provided is out of bounds. Thus we get an error. We should make sure we provide an axis that is in the range as far as dimensions of the array are concerned.

In [76]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "renuverma55/zerotoanalyst-numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/renuverma55/zerotoanalyst-numpy-array-operations


'https://jovian.ai/renuverma55/zerotoanalyst-numpy-array-operations'

## Function 5 - numpy.extract

Return the elements of an array that satisfy some condition.

numpy.extract(condition, arr)

The numpy.extract function takes two parameter .

1. Condition : An array whose nonzero or True entries indicate the elements of arr to extract.
2.arr : Input array of the same size as condition.

Returns:extract ndarray
Rank 1 array of values from arr where condition is True.


In [104]:
# Example 1 - working
arr5 = [[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]
condition = np.mod(arr5, 3)==0
print("condition", condition)

np.extract(condition, arr5)


condition [[ True False False  True]
 [False False  True False]
 [False  True False False]]


array([0, 3, 6, 9])

Output is Rank 1 array of values from arr where condition is True.

In [109]:
# Example 2 - working
a =np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
b = np.extract(a>6, a)
print(b)

[ 7  8  9 10 11]


Output is Rank 1 array of values from arr where condition is True.

In [110]:
# Example 3 - working
arr5 = np.random.randint(100,size = 150)
print("the original array is",arr5)
extracted_arr = np.extract((arr5 % 3 == 0) & (arr5 % 5 == 0),arr5)
print("The array divisible by 3 and 5 is",extracted_arr )

the original array is [47 95  9 50 28 75 11 38 37 31 45 33 21  3 99  3 52 24 32 34 33 86 94 43
 84 32 23 38 14 66 92  9 39 95 92 22 74 54 71 55 35 37 65 70 63 41 65 57
 92 81 79 43 10 51 29 78 34  2  0  0 76 29 21 70 67 36 50  9 18 26 41 26
 87  3 29 52 18 15 77 70 37 46  2 42 97 20 88 28 52 79 40 53 42 49 22 37
 79 14 83 43 12 38 92 14 37  3 74 95 45 18 14 46 95 47 37 86 48 24 15 66
 83 37 16 30 17 35 82 60 15 25  9 11 83 95 75 15 92 89  6 38 74 60 40 77
  0 27 17 28 90 15]
The array divisible by 3 and 5 is [75 45  0  0 15 45 15 30 60 15 75 15 60  0 90 15]


We can combine the multiple condition using and operator.

We can use the Numpy extract() function to extract specific elements from an array that matches the condition.

In [80]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "renuverma55/zerotoanalyst-numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/renuverma55/zerotoanalyst-numpy-array-operations


'https://jovian.ai/renuverma55/zerotoanalyst-numpy-array-operations'

## Conclusion
We have learnt about these given below functions with examples:-
* numpy.sort
* numpy.argmax
* numpy.where
* numpy.count_nonzero
* numpy.extract

We found out that there are very useful functions that can do a particular job quickly, efficiently and with less code. That’s the power of NumPy library.  

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* NumPy Documentation: https://numpy.org/doc/stable/reference/index.html

In [81]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "renuverma55/zerotoanalyst-numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/renuverma55/zerotoanalyst-numpy-array-operations


'https://jovian.ai/renuverma55/zerotoanalyst-numpy-array-operations'